### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 1

### ISSUE THREAD

**Issue by komar007** [sannies/isoviewer#8]
Hello,
I have found a situation in which this exception is thrown and isoviewer becomes unusable until it's restarted:

```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 1
	at com.sun.javafx.collections.ObservableSequentialListWrapper.get(ObservableSequentialListWrapper.java:173)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:459)
	at javafx.scene.control.ListCell.indexChanged(ListCell.java:330)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1950)
	at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
	at javafx.scene.Parent.layout(Parent.java:1076)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
	at com.sun.javafx.tk.Toolkit$$Lambda$147/1349346464.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$46/909855765.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$42/1364335809.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```
This file works correctly:
http://space.komar.be/test_ok.mp4
While this one causes the above error:
http://space.komar.be/test_fail.mp4
The second file is basically the first one with one extra pair of moof/mdat.
I cannot guarantee the files are compliant with anything.

Thanks for your work on isoviewer - I've found it very useful so far.

Best regards,
Michał

**Comment by sannies** [comment]
Hi,
the file contains multiple Track Run Boxes (trun) per fragment. This is
absolutely allowed and within the specifications but it is nevertheless a
rather rarely occuring file layout. The underlying isoparser has problems
with the file.
I'll  bugfix that asap.
Best Regards,
Sebastian
-----------------------------------------------
I'm available for freelance work.

2015-10-05 15:35 GMT+02:00 Michal Trybus <notifications@github.com>:

**Comment by sannies** [comment]
I built a new release. Works now. https://github.com/sannies/isoviewer/releases/tag/isoviewer-1.10

**Comment by komar007** [comment]
Thank you!
So this was the reason isoviewer was not showing all samples even when there was just one moof but multiple truns inside traf.
The latest version shows all of them correctly.

**Comment by sannies** [comment]
Hi Michal,

please be aware that this file layout is valid but highly inefficient.
There is a lot of overhead when samples are addressed one by one - and not
a few dozen at a time.

Best Regards,
Sebastian

2015-10-07 11:49 GMT+02:00 Michal Trybus <notifications@github.com>:

**Comment by komar007** [comment]
Hi Sebastian,

how would you go about generating an MP4 file suitable for low-latency progressive download?
My idea was that I should mux audio and video payloads so that little has to be downloaded to progress a bit in the stream (as opposed to downloading large portions of single tracks), that's why I interleaved video and audio samples and used multiple truns to describe the interleaved data.

I guess a different approach would be to have single truns inside trafs, but much more moofs. This way a single moof would contain one video trun and one audio trun. I think this might not enhance efficiency and increases header size (more moofs), so I chose not to do it. On the other hand, since moofs are shorter, the file can also be generated progressively in smaller parts which decreases latency for live content generation (since all sample data has to be known prior to generating moof).

I will soon be dealing with the problem of choosing the granularity of my muxer, but so far it sorts all samples by time, so that results in really large number of truns.

Did you mean that interleaving samples from different tracks is inefficient as such or just the approach which uses multiple truns?

Thank you very much for the advice.
Best Regards,
Michał

**Comment by sannies** [comment]
Hi Michal,
It all depends on how much control you have over the player. If your data
extraction is fully custom you might be able to push data into the decoder
while you are still downloading a segment but a typical player as they
exist today will download a full segment anyways! BUT: Download speeds
typically fluctuate a bit and if you are using this method your buffer is
razor thin. I would expect stuttering. Streaming protocols such as
Microsoft's Smooth Streaming or MPEG DASH would tpyically buffer a few
moof/mdat pairs.
I'd go for ~1 second fragments of audio/video. Either in each in its own
moof/mdat or together in one but without interleaving truns.
If you need less latency I'd say that an MP4 based protocol is not the
right choice - I'd look at something old-school like RTP.

Interleaving truns is not generally a bad idea but only if your moof/mdat
pair is of a reasonable size. Typically I'd chose trun in the range between
0,5 to 10 seconds. But never single samples as the test_fail.mp4 file
shows.

Grüße,
Sebastian




2015-10-07 16:27 GMT+02:00 Michal Trybus <notifications@github.com>:

**Comment by komar007** [comment]
Thanks again.

0.5 seconds seems reasonable for trun length, it optimized my header sizes greatly and still allows for reasonable latency on the client size if the network conditions are good enough.

Best Regards,
Michał.
